// apps/api/prisma/seeds/crisis-resources.seed.ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// CrisisType values as strings (matching the enum in the database)
// We can't import the enum directly, so we use the string literal values
async function seedCrisisResources() {
  const resources = [
    {
      id: 'kiran-mental-health',
      name: 'KIRAN Mental Health',
      type: 'HELPLINE',
      category: ['SUICIDE_RISK', 'MENTAL_HEALTH'],
      phoneNumber: '18005990019',
      whatsappNumber: null,
      email: null,
      website: 'https://www.pib.gov.in/pressreleaseshare.aspx?prid=1652240',
      state: 'All',
      city: 'All',
      available24x7: true,
      operatingHours: null,
      languages: ['hi', 'en', 'as', 'bn', 'gu', 'kn', 'ks', 'ml', 'mr', 'or', 'pa', 'ta', 'te', 'ur'],
      specialization: ['Mental Health Rehabilitation', 'Counseling'],
      ageGroups: ['all'],
      priority: 1,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Government of India initiative - National helpline for mental health support',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'vandrevala-foundation',
      name: 'Vandrevala Foundation',
      type: 'HELPLINE',
      category: ['SUICIDE_RISK', 'MENTAL_HEALTH'],
      phoneNumber: '9999666555',
      whatsappNumber: '9999666555',
      email: 'help@vandrevalafoundation.com',
      website: 'https://www.vandrevalafoundation.com/',
      state: 'All',
      city: 'All',
      available24x7: true,
      operatingHours: null,
      languages: ['en', 'hi', 'gu', 'bn', 'kn', 'ta', 'te', 'ml', 'or', 'mr'],
      specialization: ['Stress', 'Anxiety', 'Depression', 'Suicidal thoughts'],
      ageGroups: ['all'],
      priority: 2,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Also offers chat support - 24/7 helpline',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'nimhans',
      name: 'NIMHANS',
      type: 'IN_PERSON',
      category: ['MENTAL_HEALTH'],
      phoneNumber: '08046110007',
      whatsappNumber: null,
      email: 'hodneurology@nimhans.ac.in',
      website: 'https://www.nimhans.ac.in/',
      state: 'Karnataka',
      city: 'Bangalore',
      available24x7: false,
      operatingHours: 'Business Hours',
      languages: ['en', 'hi', 'kn', 'ta', 'te', 'ml'],
      specialization: ['Neurology', 'Psychiatry', 'Mental Health'],
      ageGroups: ['all'],
      priority: 3,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Primarily a research and treatment institute',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'action-for-autism',
      name: 'Action for Autism',
      type: 'HELPLINE',
      category: ['AUTISM_SUPPORT'],
      phoneNumber: '01140540991',
      whatsappNumber: null,
      email: 'actionforautism@gmail.com',
      website: 'https://www.autism-india.org/',
      state: 'Delhi',
      city: 'New Delhi',
      available24x7: false,
      operatingHours: '9am-5pm Mon-Fri',
      languages: ['en', 'hi'],
      specialization: ['Autism Spectrum Disorder', 'Diagnosis', 'Therapy', 'Support'],
      ageGroups: ['children', 'adults'],
      priority: 10,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Also has a helpline at helpline.afa@gmail.com',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'samaritans-mumbai',
      name: 'Samaritans Mumbai',
      type: 'HELPLINE',
      category: ['SUICIDE_RISK', 'SUICIDE_PREVENTION'],
      phoneNumber: '918422984528',
      whatsappNumber: null,
      email: 'talk2samaritans@gmail.com',
      website: 'https://www.samaritansmumbai.com/',
      state: 'Maharashtra',
      city: 'Mumbai',
      available24x7: false,
      operatingHours: '5pm-8pm',
      languages: ['en', 'hi', 'mr'],
      specialization: ['Suicide Prevention', 'Emotional Distress'],
      ageGroups: ['all'],
      priority: 5,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Confidential support',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'connecting-trust',
      name: 'Connecting Trust',
      type: 'HELPLINE',
      category: ['SUICIDE_RISK', 'SUICIDE_PREVENTION'],
      phoneNumber: '917030230033',
      whatsappNumber: null,
      email: 'distressmailsconnecting@gmail.com',
      website: 'https://connectingngo.org/',
      state: 'Maharashtra',
      city: 'Pune',
      available24x7: false,
      operatingHours: '12pm-8pm',
      languages: ['en', 'hi', 'mr'],
      specialization: ['Suicide Prevention', 'Emotional Distress'],
      ageGroups: ['all'],
      priority: 5,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Emotional support helpline',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'childline-india',
      name: 'Childline India',
      type: 'HELPLINE',
      category: ['CHILD_CRISIS'],
      phoneNumber: '1098',
      whatsappNumber: null,
      email: null,
      website: 'https://www.childlineindia.org.in/',
      state: 'All',
      city: 'All',
      available24x7: true,
      operatingHours: null,
      languages: ['en', 'hi', 'as', 'bn', 'gu', 'kn', 'ml', 'mr', 'or', 'pa', 'ta', 'te'],
      specialization: ['Child Protection', 'Emergency Assistance for Children'],
      ageGroups: ['children'],
      priority: 1,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'For children in distress (0-18 years)',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'women-helpline',
      name: "Women's Helpline",
      type: 'HELPLINE',
      category: ['WOMEN_CRISIS'],
      phoneNumber: '1091',
      whatsappNumber: null,
      email: null,
      website: null,
      state: 'All',
      city: 'All',
      available24x7: true,
      operatingHours: null,
      languages: ['en', 'hi'],
      specialization: ['Domestic Abuse', 'Violence against Women'],
      ageGroups: ['women'],
      priority: 1,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Activation and services may vary by state',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'ambulance-emergency',
      name: 'Ambulance',
      type: 'HELPLINE',
      category: ['MEDICAL_EMERGENCY'],
      phoneNumber: '108',
      whatsappNumber: null,
      email: null,
      website: null,
      state: 'All',
      city: 'All',
      available24x7: true,
      operatingHours: null,
      languages: ['en', 'hi'],
      specialization: ['Medical Emergencies'],
      ageGroups: ['all'],
      priority: 1,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: '108 for emergencies, 102 for patient transport (varies by state)',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'poison-control-centre',
      name: 'National Poisons Information Centre',
      type: 'HELPLINE',
      category: ['POISON_CONTROL'],
      phoneNumber: '1800116117',
      whatsappNumber: null,
      email: null,
      website: 'https://aiims.edu/index.php/hi/npic_intro',
      state: 'All',
      city: 'All',
      available24x7: true,
      operatingHours: null,
      languages: ['en', 'hi'],
      specialization: ['Poisoning'],
      ageGroups: ['all'],
      priority: 1,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Located at AIIMS, New Delhi',
      country: 'IN',
      isActive: true,
    },
    {
      id: 'humsafar-trust',
      name: 'The Humsafar Trust',
      type: 'IN_PERSON',
      category: ['LGBTQ_SUPPORT'],
      phoneNumber: '02226673731',
      whatsappNumber: null,
      email: 'info@humsafar.org',
      website: 'https://www.humsafar.org/',
      state: 'Maharashtra',
      city: 'Mumbai',
      available24x7: false,
      operatingHours: '10am-6pm Mon-Sat',
      languages: ['en', 'hi', 'mr'],
      specialization: ['LGBTQ+ Support', 'Gender & Sexual Identity'],
      ageGroups: ['all'],
      priority: 10,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: "One of India's oldest LGBTQ+ organizations",
      country: 'IN',
      isActive: true,
    },
    {
      id: 'icall-helpline',
      name: 'iCall',
      type: 'HELPLINE',
      category: ['GENERAL_COUNSELING', 'MENTAL_HEALTH'],
      phoneNumber: '9152987821',
      whatsappNumber: null,
      email: 'icall@tiss.edu',
      website: 'http://icallhelpline.org/',
      state: 'All',
      city: 'All',
      available24x7: false,
      operatingHours: '10am-8pm Mon-Sat',
      languages: ['en', 'hi', 'mr', 'gu', 'ta', 'te', 'ml', 'kn'],
      specialization: ['Mental Health', 'Psychosocial counseling'],
      ageGroups: ['all'],
      priority: 3,
      isVerified: true,
      verifiedAt: new Date('2025-09-30'),
      description: 'Run by the Tata Institute of Social Sciences',
      country: 'IN',
      isActive: true,
    }
  ];

  for (const resource of resources) {
    try {
      await prisma.crisisResource.upsert({
        where: { id: resource.id },
        update: {
          ...resource,
          category: { set: resource.category as any }, // Cast to any to bypass type error
        },
        create: {
          ...resource,
          category: { set: resource.category as unknown as import('@prisma/client').CrisisType[] },
        },
      });
      console.log(`✅ Added/Updated: ${resource.name}`);
    } catch (error: any) {
      console.error(`❌ Error processing ${resource.name}:`, error.message);
    }
  }
}

async function main() {
  console.log('🌱 Seeding crisis resources...\n');
  
  await seedCrisisResources();
  
  const count = await prisma.crisisResource.count();
  console.log(`\n✅ Seeding complete! Total resources: ${count}`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });